#define     BINARY_OP       257
#define     UNI_OP          258
#define     SIGNO_BIN_OP    259
#define     ASIGNACION      260
#define     MAIN            261
#define     SI              262
#define     MIENTRAS        263
#define     INI_DECLARACION 264
#define     FIN_DECLARACION 265
#define     LEER            266
#define     HACER           267
#define     HASTA           268
#define     BOOLEANOS       269
#define     PUN_COMA        270
#define     SEPARADOR       271
#define     PAR_IZQ         272
#define     PAR_DER         273
#define     OUT             274
#define     DEVOLVER        275
#define     COR_IZQ         276
#define     COR_DER         277
#define     CONST_INT       278
#define     CONST_FLOAT     279
#define     CONST_CHAR      280
#define     CONST_STRING    281
#define     IDENTIFICADOR   282
#define     TIPO            283
#define     INICIO_BLOQUE   284
#define     FIN_BLOQUE      285